### ISSUE TITLE
SoD P4 broke tukui

### ISSUE THREAD

**Issue by emsimpson92** [tukui-org/Tukui#157] opened 2024-07-13 05:04 UTC
Nothing works. Last update was a while ago. Please fix tukui because elvui just isn't as good.

**Comment by Repooc** [comment] 2024-07-13 07:11
Issue is vague, will assume duplicate of #156

**Closed as completed** 2024-07-13 07:11 UTC

**Comment by emsimpson92** [comment] 2024-07-13 15:13
Yes, it is likely a duplicate. It may sound vague, but I mean _nothing_ works. I don't have the help menu button, none of the modules appear to be working, and the most I can bring up is the splash screen if I type /tukui

**Comment by Repooc** [comment] 2024-07-13 19:53
and as stated in the other ticket, its loading if u use the dev build (not the release build)

**Comment by Repooc** [comment] 2024-07-13 19:58
If you have errors after installing, its best to give the information it errors about, saying "Tukui won't load" wont help, actual error messages help find issues, but you should be on the dev build first to ensure u are not reporting errors that are fixed but not released
